### ISSUE TITLE
Dead Domains Linter broken

### ISSUE THREAD

**Issue by jarelllama** [jarelllama/Scam-Blocklist#395]
@hagezi @xRuffKez @iam-py-test, the Adguard Dead Domains Linter has suddenly broke for me. Any chance you could test if this error happens on your side too?

``` console
$ dead-domains-linter 
(node:8193) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
/usr/local/lib/node_modules/@adguard/dead-domains-linter/src/cli.js:97
    consola.info(`Starting ${packageJson.name} v${packageJson.version}`);
            ^

TypeError: consola.info is not a function
    at main (/usr/local/lib/node_modules/@adguard/dead-domains-linter/src/cli.js:97:13)
    at Object.<anonymous> (/usr/local/lib/node_modules/@adguard/dead-domains-linter/src/cli.js:167:1)
    at Module._compile (node:internal/modules/cjs/loader:1740:14)
    at Object..js (node:internal/modules/cjs/loader:1905:10)
    at Module.load (node:internal/modules/cjs/loader:1474:32)
    at Function._load (node:internal/modules/cjs/loader:1286:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:234:24)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:151:5)
    at node:internal/main/run_main_module:33:47

Node.js v23.5.0
```

**Comment by jarelllama** [comment]
Fix is on it's way just a few minutes after I reported. Props to the AdGuard team.
https://github.com/AdguardTeam/DeadDomainsLinter/issues/32

**Comment by xRuffKez** [comment]
Debug further with
```
node --trace-deprecation
```

**Comment by hagezi** [comment]
Works for me on my local Debian build system.

**Comment by jarelllama** [comment]
Fixed by Adguard
